<?php

namespace Tests;

use Faker\Factory;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Database\Factories\UserFactory;


abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseMigrations, HasFactory;

    protected $faker;

    public function setUp(): void{
        parent::setUp(); // TODO: Change the autogenerated stub
       $this->faker = Factory::create();
    }
}
